export const Animals = [
  {"word": "Elephant", "hint": "Largest land mammal with tusks."},
  {"word": "Tiger", "hint": "Large striped cat found in Asia."},
  {"word": "Giraffe", "hint": "Tall African mammal with a long neck."},
  {"word": "Kangaroo", "hint": "Australian marsupial known for hopping."},
  {"word": "Penguin", "hint": "Flightless bird that swims in the Southern Hemisphere."},
  {"word": "Lion", "hint": "Big cat known as the 'king of the jungle'."},
  {"word": "Dolphin", "hint": "Intelligent marine mammal known for its playful behavior."},
  {"word": "Butterfly", "hint": "Insect with colorful wings."},
  {"word": "Panda", "hint": "Bear native to China with distinctive black and white fur."},
  {"word": "Zebra", "hint": "African animal with black and white stripes."},
  {"word": "Ostrich", "hint": "Large flightless bird with long legs."},
  {"word": "Hippo", "hint": "Large herbivorous mammal that spends much time in water."},
  {"word": "Sloth", "hint": "Slow-moving mammal found in Central and South America."},
  {"word": "Koala", "hint": "Australian marsupial known for eating eucalyptus leaves."},
  {"word": "Gorilla", "hint": "Largest primate, native to Africa."},
  {"word": "Fox", "hint": "Wild canine known for its cunning."},
  {"word": "Rhino", "hint": "Large African mammal with a horn on its nose."},
  {"word": "Polar Bear", "hint": "Arctic bear adapted for a cold climate."},
  {"word": "Octopus", "hint": "Sea creature with eight tentacles."},
  {"word": "Jaguar", "hint": "Large wild cat native to the Americas."}
]

export const Art = [
  {"word": "Palette", "hint": "Artist's tool for mixing colors."},
  {"word": "Sculpture", "hint": "Three-dimensional art form."},
  {"word": "Impressionism", "hint": "Art movement known for its loose brushwork."},
  {"word": "Canvas", "hint": "Surface for painting."},
  {"word": "Mosaic", "hint": "Artwork made of small pieces of colored glass or tile."},
  {"word": "Portrait", "hint": "Painting or photograph of a person."},
  {"word": "Abstract", "hint": "Art style that does not depict objects realistically."},
  {"word": "Sketch", "hint": "Quick drawing."},
  {"word": "Gallery", "hint": "Place where art is displayed."},
  {"word": "Pottery", "hint": "Art of making ceramic objects."},
  {"word": "Calligraphy", "hint": "Art of decorative handwriting."},
  {"word": "Fresco", "hint": "Painting technique using wet plaster."},
  {"word": "Still Life", "hint": "Artwork depicting inanimate objects."},
  {"word": "Watercolor", "hint": "Painting technique using water-based paints."},
  {"word": "Chiaroscuro", "hint": "Artistic technique of using strong contrasts between light and dark."},
  {"word": "Engraving", "hint": "Art of cutting or carving a design into a hard surface."},
  {"word": "Collage", "hint": "Artwork created by assembling different materials."},
  {"word": "Surrealism", "hint": "Art movement that explores dreams and the unconscious."},
  {"word": "Etching", "hint": "Printmaking technique using acid to bite into a metal plate."},
  {"word": "Cubism", "hint": "Art movement that depicts subjects from multiple viewpoints."}
]

export const Bollywood = [
  {"word": "Sholay", "hint": "Classic Bollywood film known for its iconic characters Jai and Veeru."},
  {"word": "3 Idiots", "hint": "Comedy-drama about three engineering students challenging traditional education."},
  {"word": "Lagaan", "hint": "Sports drama set during British rule in India, focusing on a cricket match."},
  {"word": "Dilwale Dulhania Le Jayenge", "hint": "Romantic film starring Shah Rukh Khan and Kajol, set in Europe."},
  {"word": "Baahubali", "hint": "Epic fantasy film series directed by SS Rajamouli, known for its grandeur."},
  {"word": "Andaz Apna Apna", "hint": "Comedy film starring Aamir Khan and Salman Khan, known for its humor."},
  {"word": "Bajrangi Bhaijaan", "hint": "Drama film starring Salman Khan, about a man's journey to reunite a girl with her family."},
  {"word": "Kabhi Khushi Kabhie Gham", "hint": "Family drama featuring an ensemble cast including Shah Rukh Khan and Amitabh Bachchan."},
  {"word": "Gangs of Wasseypur", "hint": "Crime drama film directed by Anurag Kashyap, known for its gritty portrayal."},
  {"word": "Mughal-e-Azam", "hint": "Historical epic film set in the Mughal era, known for its grand production values."},
  {"word": "Chak De! India", "hint": "Sports drama starring Shah Rukh Khan, about a disgraced hockey player turned coach."},
  {"word": "Om Shanti Om", "hint": "Musical romantic drama starring Shah Rukh Khan and Deepika Padukone, with a reincarnation theme."},
  {"word": "Lage Raho Munna Bhai", "hint": "Comedy-drama film starring Sanjay Dutt, known for its Gandhian philosophy."},
  {"word": "Queen", "hint": "Comedy-drama about a woman on a solo honeymoon trip after her wedding is called off."},
  {"word": "A Wednesday", "hint": "Thriller film starring Naseeruddin Shah, known for its intense storyline."},
  {"word": "Rang De Basanti", "hint": "Drama film about a group of friends who become activists."},
  {"word": "Devdas", "hint": "Romantic drama based on the novel by Sarat Chandra Chattopadhyay."},
  {"word": "Munna Bhai MBBS", "hint": "Comedy-drama film starring Sanjay Dutt, known for its humorous take on medical education."},
  {"word": "Chennai Express", "hint": "Action comedy film starring Shah Rukh Khan and Deepika Padukone, set in South India."},
  {"word": "Drishyam", "hint": "Thriller film starring Ajay Devgn, about a man's attempts to cover up a crime."},
]

export const Food = [
  {"word": "Pizza", "hint": "Italian dish with a crust, tomato sauce, and toppings."},
  {"word": "Burger", "hint": "Sandwich with a patty, often served with cheese and vegetables."},
  {"word": "Pasta", "hint": "Italian noodles typically made from durum wheat."},
  {"word": "Sushi", "hint": "Japanese dish consisting of rice and raw fish or seafood."},
  {"word": "Taco", "hint": "Mexican dish with a folded or rolled tortilla filled with various ingredients."},
  {"word": "Steak", "hint": "Slice of meat, typically beef, cooked by grilling or frying."},
  {"word": "Salad", "hint": "Mix of vegetables, often served with dressing."},
  {"word": "Sandwich", "hint": "Two slices of bread with a filling between them."},
  {"word": "Soup", "hint": "Liquid food made by boiling ingredients like vegetables, meat, or fish."},
  {"word": "Burrito", "hint": "Mexican dish with a flour tortilla wrapped around a filling."},
  {"word": "Curry", "hint": "Spicy dish with a sauce, often served with rice."},
  {"word": "Ravioli", "hint": "Italian pasta with filling sealed between two layers of thin pasta dough."},
  {"word": "Cheese", "hint": "Dairy product made from milk."},
  {"word": "Fries", "hint": "Thin strips of potato deep-fried until crisp."},
  {"word": "Donut", "hint": "Sweet fried dough ring, often glazed or filled."},
  {"word": "Pancake", "hint": "Flat cake, often round, made from batter and cooked on a griddle."},
  {"word": "Muffin", "hint": "Small, round bread typically sweet and baked."},
  {"word": "Smoothie", "hint": "Thick beverage made from blended fruits and sometimes yogurt or milk."},
  {"word": "Waffle", "hint": "Batter cooked between two plates, typically with a grid pattern."},
  {"word": "Lasagna", "hint": "Italian dish made of layers of pasta, sauce, and cheese."},
]

export const Geography = [
  {"word": "Mountain", "hint": "High, steep landform, such as Everest or Kilimanjaro."},
  {"word": "River", "hint": "Large natural stream of water flowing in a channel to the sea, a lake, or another river."},
  {"word": "Island", "hint": "Landmass surrounded by water."},
  {"word": "Peninsula", "hint": "Piece of land almost surrounded by water or projecting out into a body of water."},
  {"word": "Desert", "hint": "Arid land with little or no vegetation."},
  {"word": "Volcano", "hint": "Opening in the Earth's crust through which molten lava, ash, and gases erupt."},
  {"word": "Plateau", "hint": "Flat elevated landform, such as the Tibetan Plateau."},
  {"word": "Glacier", "hint": "Large persistent body of ice that forms where the accumulation of snow exceeds its ablation (melting and sublimation) over many years."},
  {"word": "Canyon", "hint": "Deep, narrow valley with steep sides."},
  {"word": "Delta", "hint": "Triangular tract of sediment deposited at the mouth of a river."},
  {"word": "Archipelago", "hint": "Group of islands."},
  {"word": "Cape", "hint": "Headland extending into a body of water."},
  {"word": "Fjord", "hint": "Long, narrow inlet with steep sides or cliffs, created by glacial erosion."},
  {"word": "Oasis", "hint": "Fertile area in a desert, typically surrounding a water source."},
  {"word": "Tundra", "hint": "Treeless plain characteristic of Arctic and subarctic regions."},
  {"word": "Rainforest", "hint": "Lush forest with heavy annual rainfall, typically in the tropics."},
  {"word": "Savanna", "hint": "Grassy plain with scattered trees, found in tropical and subtropical regions."},
  {"word": "Estuary", "hint": "Partially enclosed coastal body of water where freshwater from rivers and streams meets and mixes with saltwater from the ocean."},
  {"word": "Atoll", "hint": "Ring-shaped coral reef including a coral rim that encircles a lagoon partially or completely."},
  {"word": "Continental Shelf", "hint": "Underwater extension of a continent, which slopes gently down from the shore before dropping steeply to the ocean floor."},
]

export const Literature = [
  {"word": "Novel", "hint": "Long fictional narrative."},
  {"word": "Poetry", "hint": "Literary work in verse, often with heightened language."},
  {"word": "Drama", "hint": "Literary genre intended for performance, typically involving dialogue and conflict."},
  {"word": "Protagonist", "hint": "Main character in a literary work."},
  {"word": "Antagonist", "hint": "Character or force in conflict with the protagonist."},
  {"word": "Sonnet", "hint": "Poem of fourteen lines using any of a number of formal rhyme schemes."},
  {"word": "Metaphor", "hint": "Figure of speech comparing two unlike things without using 'like' or 'as'."},
  {"word": "Symbolism", "hint": "Use of symbols to represent ideas or qualities."},
  {"word": "Satire", "hint": "Literary work that ridicules human vices and follies."},
  {"word": "Allegory", "hint": "Narrative in which characters, actions, or settings represent abstract ideas or moral qualities."},
  {"word": "Fiction", "hint": "Literature based on imagination rather than fact."},
  {"word": "Biography", "hint": "Account of a person's life written by someone else."},
  {"word": "Autobiography", "hint": "Account of a person's life written by that person."},
  {"word": "Genre", "hint": "Category of literary composition characterized by a particular style, form, or content."},
  {"word": "Plot", "hint": "Sequence of events in a literary work."},
  {"word": "Characterization", "hint": "Creation or construction of a fictional character."},
  {"word": "Conflict", "hint": "Struggle between opposing forces in a literary work."},
  {"word": "Irony", "hint": "Expression of one's meaning by using language that normally signifies the opposite, typically for humorous or emphatic effect."},
  {"word": "Narrative", "hint": "Story or account of events, experiences, or the like, whether true or fictitious."},
  {"word": "Alliteration", "hint": "Repetition of initial consonant sounds in words close to each other."},
]

export const Math = [
  {"word": "Addition", "hint": "Mathematical operation of combining numbers."},
  {"word": "Subtraction", "hint": "Mathematical operation of taking away one number from another."},
  {"word": "Multiplication", "hint": "Mathematical operation of repeated addition."},
  {"word": "Division", "hint": "Mathematical operation of splitting a number into equal parts."},
  {"word": "Fraction", "hint": "Numerical quantity expressed in the form a/b, where a is the numerator and b is the denominator."},
  {"word": "Decimal", "hint": "Numerical system based on powers of ten, often represented with a decimal point."},
  {"word": "Equation", "hint": "Mathematical statement asserting that two expressions are equal."},
  {"word": "Variable", "hint": "Symbol or letter representing a quantity that can vary."},
  {"word": "Function", "hint": "Relation between a set of inputs and a set of possible outputs, where each input is related to exactly one output."},
  {"word": "Graph", "hint": "Visual representation of data, typically shown on a coordinate plane."},
  {"word": "Geometry", "hint": "Branch of mathematics dealing with shapes, sizes, and properties of space."},
  {"word": "Algebra", "hint": "Branch of mathematics dealing with symbols and the rules for manipulating those symbols."},
  {"word": "Probability", "hint": "Likelihood of a specific outcome or event occurring."},
  {"word": "Statistics", "hint": "Branch of mathematics dealing with the collection, analysis, interpretation, and presentation of data."},
  {"word": "Prime Number", "hint": "Number greater than 1 that has no positive divisors other than 1 and itself."},
  {"word": "Ratio", "hint": "Comparison of two quantities by division."},
  {"word": "Exponent", "hint": "Number that indicates how many times a base number is multiplied by itself."},
  {"word": "Quadratic", "hint": "Equation involving a term with a degree of two, like ax^2 + bx + c = 0."},
  {"word": "Polygon", "hint": "Closed plane figure bounded by straight sides."},
  {"word": "Integral", "hint": "Mathematical concept representing the area under a curve."},
]

export const Music = [
  {"word": "Dilbar", "hint": "Hit song featuring Nora Fatehi in a Bollywood movie."},
  {"word": "Chaiyya Chaiyya", "hint": "Iconic song featuring Shah Rukh Khan dancing on top of a train."},
  {"word": "Tum Hi Ho", "hint": "Chartbuster song from the movie 'Aashiqui 2', known for its emotional melody."},
  {"word": "Senorita", "hint": "Popular song from the movie 'Zindagi Na Milegi Dobara', featuring Hrithik Roshan and Katrina Kaif."},
  {"word": "Ghungroo", "hint": "Upbeat song from the movie 'War', featuring Hrithik Roshan and Vaani Kapoor."},
  {"word": "Kabira", "hint": "Soulful song from the movie 'Yeh Jawaani Hai Deewani', featuring Ranbir Kapoor and Deepika Padukone."},
  {"word": "Badtameez Dil", "hint": "Energetic song from the movie 'Yeh Jawaani Hai Deewani', featuring Ranbir Kapoor."},
  {"word": "Chammak Challo", "hint": "Popular song from the movie 'Ra.One', featuring Shah Rukh Khan and Kareena Kapoor."},
  {"word": "Tera Ghata", "hint": "Breakup song that became a viral hit."},
  {"word": "Gerua", "hint": "Romantic song from the movie 'Dilwale', featuring Shah Rukh Khan and Kajol."},
  {"word": "Despacito", "hint": "Spanish-English song that gained international popularity."},
  {"word": "Kala Chashma", "hint": "Peppy song from the movie 'Baar Baar Dekho', featuring Sidharth Malhotra and Katrina Kaif."},
  {"word": "Nashe Si Chadh Gayi", "hint": "Hit song from the movie 'Befikre', featuring Ranveer Singh and Vaani Kapoor."},
  {"word": "Zingaat", "hint": "Upbeat Marathi-Hindi song from the movie 'Dhadak', featuring Ishaan Khatter and Janhvi Kapoor."},
  {"word": "Dil Diyan Gallan", "hint": "Romantic song from the movie 'Tiger Zinda Hai', featuring Salman Khan and Katrina Kaif."},
  {"word": "Kamli", "hint": "Energetic song from the movie 'Dhoom 3', featuring Katrina Kaif."},
  {"word": "Ban Ja Rani", "hint": "Romantic song featuring Guru Randhawa."},
  {"word": "Ae Dil Hai Mushkil", "hint": "Title track from the movie 'Ae Dil Hai Mushkil', featuring Ranbir Kapoor and Anushka Sharma."},
  {"word": "Hawa Hawa", "hint": "Remake of a popular 80s song, featuring Arjun Kapoor and Ileana D'Cruz."},
  {"word": "Bom Diggy Diggy", "hint": "Upbeat party song featuring Kartik Aaryan and Sunny Singh."},
]

export const Science = [
  {"word": "Gravity", "hint": "Force that attracts objects toward the center of the Earth."},
  {"word": "DNA", "hint": "Molecule that carries genetic instructions for the development, functioning, growth, and reproduction of all known organisms."},
  {"word": "Atom", "hint": "Basic unit of matter composed of protons, neutrons, and electrons."},
  {"word": "Evolution", "hint": "Process by which species change over time."},
  {"word": "Galaxy", "hint": "System of stars, stellar remnants, interstellar gas, dust, dark matter, and other objects bound together by gravitational forces."},
  {"word": "Photosynthesis", "hint": "Process by which green plants and some other organisms use sunlight to synthesize foods with the help of chlorophyll."},
  {"word": "Electricity", "hint": "Form of energy resulting from the movement of electrons."},
  {"word": "Solar System", "hint": "Collection of planets and their moons in orbit around a star, together with smaller bodies such as asteroids, meteoroids, and comets."},
  {"word": "Chemistry", "hint": "Branch of science dealing with the composition, structure, properties, and reactions of matter."},
  {"word": "Ecosystem", "hint": "Community of living organisms (plants, animals, and microbes) in conjunction with the nonliving components of their environment (such as air, water, and mineral soil)."},
  {"word": "Mutation", "hint": "Change in the DNA sequence of a cell's genome."},
  {"word": "Hypothesis", "hint": "Proposed explanation based on limited evidence as a starting point for further investigation."},
  {"word": "Molecule", "hint": "Group of atoms bonded together, representing the smallest fundamental unit of a chemical compound."},
  {"word": "Acceleration", "hint": "Rate of change of velocity."},
  {"word": "Biology", "hint": "Study of living organisms, divided into many specialized fields."},
  {"word": "Fossil", "hint": "Remains or impression of a prehistoric organism preserved in petrified form."},
  {"word": "Neutron", "hint": "Subatomic particle found in the nucleus of an atom, with no net electric charge."},
  {"word": "Meteorology", "hint": "Study of atmospheric phenomena, especially weather and climate."},
  {"word": "Einstein", "hint": "Physicist known for the theory of relativity and the equation E=mc^2."},
  {"word": "Biotechnology", "hint": "Use of living systems and organisms to develop or make useful products."},
]

export const Sports = [
  {"word": "Football", "hint": "Popular sport played with a round ball and two teams of eleven players each."},
  {"word": "Basketball", "hint": "Sport played on a rectangular court with two teams of five players each, aiming to score points by throwing a ball through a hoop."},
  {"word": "Tennis", "hint": "Racket sport played individually against a single opponent (singles) or between two teams of two players each (doubles), on a rectangular court with a net."},
  {"word": "Golf", "hint": "Sport played on a large outdoor course, where players use clubs to hit a small ball into a series of holes in as few strokes as possible."},
  {"word": "Cricket", "hint": "Bat-and-ball game played between two teams of eleven players each on a field with a rectangular 22-yard-long pitch."},
  {"word": "Baseball", "hint": "Bat-and-ball game played between two teams of nine players each, where players score runs by hitting a ball and running around four bases arranged in a diamond shape."},
  {"word": "Hockey", "hint": "Sport played on a field or rink, where players use a stick to hit a small ball or puck into the opponent's goal."},
  {"word": "Soccer", "hint": "Alternative name for football, widely used in some countries, especially in North America."},
  {"word": "Swimming", "hint": "Sport or activity of moving through water by using the limbs."},
  {"word": "Athletics", "hint": "Collection of sporting events that involve competitive running, jumping, throwing, and walking."},
  {"word": "Boxing", "hint": "Combat sport where two opponents fight using their fists in a ring."},
  {"word": "Cycling", "hint": "Sport or activity of riding a bicycle."},
  {"word": "Rugby", "hint": "Contact team sport that originated in England, played with an oval ball and two teams of fifteen players each."},
  {"word": "Volleyball", "hint": "Sport played by two teams of six players each, where players use their hands to hit a ball over a high net."},
  {"word": "Badminton", "hint": "Racket sport played with a shuttlecock across a net."},
  {"word": "Gymnastics", "hint": "Sport involving exercises and performances requiring physical strength, flexibility, balance, agility, coordination, and endurance."},
  {"word": "Wrestling", "hint": "Combat sport involving grappling type techniques such as clinch fighting, throws and takedowns, joint locks, pins and other grappling holds."},
  {"word": "Karate", "hint": "Martial art developed in Japan that uses punches, kicks, knee strikes, elbow strikes, and open-hand techniques."},
  {"word": "Sailing", "hint": "Sport or activity of using boats with sails."},
  {"word": "Table Tennis", "hint": "Indoor sport played on a table divided by a net, with players using paddles to hit a lightweight ball back and forth."},
]

export const Technology = [
  {"word": "Algorithm", "hint": "Step-by-step procedure or formula for solving a problem."},
  {"word": "Artificial Intelligence", "hint": "Branch of computer science that deals with creating machines capable of performing tasks that typically require human intelligence."},
  {"word": "Encryption", "hint": "Process of converting information into a code to prevent unauthorized access."},
  {"word": "Database", "hint": "Structured set of data held in a computer, typically organized for rapid search and retrieval."},
  {"word": "Virtual Reality", "hint": "Computer-generated simulation of a three-dimensional environment that can be interacted with in a seemingly real or physical way by a person using special electronic equipment."},
  {"word": "Cybersecurity", "hint": "Protection of computer systems and networks from the theft of or damage to their hardware, software, or electronic data."},
  {"word": "Cloud Computing", "hint": "Delivery of computing services—servers, storage, databases, networking, software, analytics, and more—over the Internet."},
  {"word": "Blockchain", "hint": "Distributed ledger technology that records transactions across multiple computers in a way that is secure, transparent, and resistant to modification."},
  {"word": "Machine Learning", "hint": "Field of study that gives computers the ability to learn without being explicitly programmed."},
  {"word": "Robotics", "hint": "Design, construction, operation, and use of robots."},
  {"word": "Internet of Things", "hint": "Network of physical devices, vehicles, home appliances, and other items embedded with electronics, software, sensors, actuators, and connectivity which enables these objects to connect and exchange data."},
  {"word": "Augmented Reality", "hint": "Technology that superimposes a computer-generated image on a user's view of the real world, thus providing a composite view."},
  {"word": "Biometrics", "hint": "Measurement and statistical analysis of people's unique physical and behavioral characteristics."},
  {"word": "Big Data", "hint": "Extremely large data sets that may be analyzed computationally to reveal patterns, trends, and associations, especially relating to human behavior and interactions."},
  {"word": "Wi-Fi", "hint": "Wireless networking technology that uses radio waves to provide high-speed internet and network connections."},
  {"word": "3D Printing", "hint": "Additive manufacturing process that creates a three-dimensional object by layering materials."},
  {"word": "Artificial Neural Network", "hint": "Computational model inspired by the way biological neural networks in the human brain process information."},
  {"word": "GPS", "hint": "Global Positioning System, a satellite-based navigation system that provides location and time information anywhere on Earth."},
  {"word": "Biotechnology", "hint": "Use of living systems and organisms to develop or make useful products, or any technological application that uses biological systems, living organisms, or derivatives thereof, to make or modify products or processes for specific use."},
  {"word": "Quantum Computing", "hint": "Area of computing focused on developing computer technology based on the principles of quantum theory, which explains the behavior of energy and material on the atomic and subatomic levels."},
]

export const VideoGames = [
  {"word": "Mario", "hint": "Iconic plumber character from Nintendo."},
  {"word": "Zelda", "hint": "Adventure game series featuring Link and Princess Zelda."},
  {"word": "Pokémon", "hint": "Popular franchise where players capture and train creatures."},
  {"word": "Fortnite", "hint": "Online multiplayer battle royale game."},
  {"word": "Minecraft", "hint": "Sandbox game where players build structures and explore worlds."},
  {"word": "Call of Duty", "hint": "First-person shooter franchise known for its realistic warfare settings."},
  {"word": "World of Warcraft", "hint": "Massively multiplayer online role-playing game (MMORPG) by Blizzard Entertainment."},
  {"word": "Final Fantasy", "hint": "Long-running role-playing game series by Square Enix."},
  {"word": "Tetris", "hint": "Puzzle game where players arrange falling blocks."},
  {"word": "League of Legends", "hint": "Multiplayer online battle arena (MOBA) game by Riot Games."},
  {"word": "Overwatch", "hint": "Team-based multiplayer first-person shooter game."},
  {"word": "Super Smash Bros.", "hint": "Fighting game featuring Nintendo characters."},
  {"word": "Fortnite", "hint": "Online multiplayer battle royale game."},
  {"word": "FIFA", "hint": "Popular soccer (football) simulation game series by EA Sports."},
  {"word": "The Sims", "hint": "Life simulation game where players control virtual people."},
  {"word": "GTA", "hint": "Open-world action-adventure game series by Rockstar Games."},
  {"word": "Assassin's Creed", "hint": "Action-adventure game series with historical settings."},
  {"word": "Dota", "hint": "Multiplayer online battle arena (MOBA) game by Valve Corporation."},
  {"word": "Pac-Man", "hint": "Classic arcade game where players navigate a maze and eat dots."},
  {"word": "Splatoon", "hint": "Third-person shooter game where players control characters that can transform between humanoid and squid forms."},
]

// module.exports = Animals;
// module.exports = Art;
// module.exports = Bollywood;
// module.exports = Food;
// module.exports = Geography;
// module.exports = Literature;
// module.exports = Math;
// module.exports = Music;
// module.exports = Science;
// module.exports = Sports;
// module.exports = Technology;
// module.exports = VideoGames;
